 /* ************ xsvobo1x_xkuzni04.sql ************ *
 *              Databázové systémy (IDS)            *
 *    Lucie Svobodová, xsvobo1x@stud.fit.vutbr.cz   *
 *      Jakub Kuzník, xkuzni04@stud.fit.vutbr.cz    *
 *                 FIT VUT 2021/2022                *
 *  *********************************************** */

/* DROP TABLES */
DROP TABLE Platba;
DROP TABLE Objednavka_obsahuje_pokrm_napoj;
DROP TABLE Objednavk;
DROP TABLE Rezervace_stolu;
DROP TABLE Rezervace;
DROP TABLE Ingredience_v_pokrmu_napoji;
DROP TABLE Pokrm_napoj;
DROP TABLE Ingredience_obsahuje_alergen;
DROP TABLE Alergen;
DROP TABLE Ingredience;
DROP TABLE Telefon;
DROP TABLE Zamestnanec;
DROP TABLE Pozice;
DROP TABLE Zakaznik;
DROP TABLE Stul;
DROP TABLE Mistnost;


/* CREATE EMPTY TABLES */
CREATE TABLE Mistnost (
    cislo_mistnosti         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nazev                   VARCHAR(128),
    kapacita                SMALLINT CHECK (kapacita>0),
    CONSTRAINT PK_mistnost  PRIMARY KEY (cislo_mistnosti)
);

CREATE TABLE Stul (
    cislo_stolu       NUMERIC(3,0),
    cislo_mistnosti   NUMBER,
    pocet_mist        SMALLINT DEFAULT '4',
    CONSTRAINT PK_stul_mistnost PRIMARY KEY (cislo_stolu, cislo_mistnosti),
    CONSTRAINT FK_stul_mistnost FOREIGN KEY (cislo_mistnosti) REFERENCES Mistnost
);

CREATE TABLE Zakaznik (
    ID_zakaznik     NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    jmeno           VARCHAR(32) NOT NULL,
    prijmeni        VARCHAR(32) NOT NULL,
    telefon         VARCHAR(32) NOT NULL CONSTRAINT zakaznik_telefon_format CHECK (LENGTH(telefon) = 9),
    email           VARCHAR(64) CONSTRAINT email_format CHECK (REGEXP_LIKE (email, '^\w+(\.\w+)*@\w+(\.\w+)+$')),
    CONSTRAINT PK_zakaznik PRIMARY KEY (ID_zakaznik)
);

CREATE TABLE Pozice (
    zkratka_pozice VARCHAR(32),
    nazev_pozice   VARCHAR(255) UNIQUE NOT NULL,
    CONSTRAINT PK_pozice PRIMARY KEY (zkratka_pozice)
);

CREATE TABLE Zamestnanec (
    ID_zamestnanec  NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    zkratka_pozice  VARCHAR(32)    NOT NULL,
    jmeno           VARCHAR(32)    NOT NULL,
    prijmeni        VARCHAR(32)    NOT NULL,
    rodne_cislo     VARCHAR(32)    NOT NULL         /* zadáváno bez lomítka */
                         CONSTRAINT rc_format  CHECK (REGEXP_LIKE (rodne_cislo, '^(\d{9}|\d{10})$')
                                                AND (MOD(TO_NUMBER(rodne_cislo), 11) = 0)),
    bankovni_ucet   VARCHAR(64)    NOT NULL
                        CONSTRAINT bank_format CHECK (REGEXP_LIKE (bankovni_ucet, '^\d+-?\d*\/\d{4}$')
                                                AND LENGTH(bankovni_ucet) > 6 AND LENGTH(bankovni_ucet) < 23),
    adresa          VARCHAR(255),
    CONSTRAINT PK_zamestnanec PRIMARY KEY (ID_zamestnanec),
    CONSTRAINT FK_pozice      FOREIGN KEY (zkratka_pozice) REFERENCES Pozice
);

CREATE TABLE Telefon (
    poradove_cislo  NUMERIC(2,0)  DEFAULT '1',
    ID_zamestnanec  NUMBER        NOT NULL,
    telefon         VARCHAR(32)   NOT NULL  CONSTRAINT telefon_format CHECK (LENGTH(telefon) = 9),
    CONSTRAINT PK_telefon_zamestnanec  PRIMARY KEY (poradove_cislo, ID_zamestnanec),
    CONSTRAINT FK_tel_zamestnanec      FOREIGN KEY (ID_zamestnanec) REFERENCES Zamestnanec
);

CREATE TABLE Ingredience (
    ID_ingredience  NUMBER GENERATED ALWAYS as IDENTITY,
    nazev           VARCHAR(255) NOT NULL,
    CONSTRAINT PK_ingredience PRIMARY KEY (ID_ingredience)
);

CREATE TABLE Alergen (
    ID_alergen      NUMERIC(2, 0),
    nazev           varchar(32) NOT NULL,
    CONSTRAINT PK_alergen PRIMARY KEY (ID_alergen)
);

CREATE TABLE Ingredience_obsahuje_alergen (
    ID_ingredience  NUMBER NOT NULL,
    ID_alergen      NUMBER NOT NULL,
    CONSTRAINT FK_inal_ingredience FOREIGN KEY (ID_ingredience) REFERENCES Ingredience,
    CONSTRAINT FK_inal_alergen     FOREIGN KEY (ID_alergen)     REFERENCES Alergen
);

/* Generalizace/specializace:
                                        Pokrm_napoj
                                             △
                                          ___|___
                                         |       |
                                       Pokrm    Napoj

   Zvolili jsme způsob reprezentace pomocí jedné tabulky (Pokrm_napoj) pro obě
   specializace, protože specializace Pokrm a Napoj jsou disjunktní a totální.
*/
CREATE TABLE Pokrm_napoj (
    ID_pokrm_napoj  NUMBER GENERATED ALWAYS as IDENTITY,
    nazev           VARCHAR(255) NOT NULL,
    typ             VARCHAR(8)   DEFAULT 'pokrm' NOT NULL
                        CONSTRAINT pokrm_napoj_typ CHECK (typ IN ('pokrm', 'nápoj')),
    doba_pripravy   VARCHAR(32),
    hmotnost_gram   INT CHECK (hmotnost_gram > 0),
    obsah_alkoholu  NUMERIC(5, 2) CHECK (obsah_alkoholu >= 0.0),
    objem_ml        INT CHECK (objem_ml > 0),
    cena            INT NOT NULL CHECK (cena > 0),
    CONSTRAINT PK_pokrm_napoj PRIMARY KEY (ID_pokrm_napoj)
);

CREATE TABLE Ingredience_v_pokrmu_napoji (
    ID_pokrm_napoj  NUMBER NOT NULL,
    ID_ingredience  NUMBER NOT NULL,
    mnozstvi        INT CHECK (mnozstvi > 0),
    CONSTRAINT FK_invpn_pokrm_napoj FOREIGN KEY (ID_pokrm_napoj) REFERENCES Pokrm_napoj,
    CONSTRAINT FK_invpn_ingredience FOREIGN KEY (ID_ingredience) REFERENCES Ingredience
);

CREATE TABLE Rezervace (
    ID_rezervace            NUMBER GENERATED ALWAYS as IDENTITY,
    ID_zamestnanec          NUMBER          NOT NULL,
    ID_zakaznik             NUMBER          NOT NULL,
    datum_rezervace         DATE            DEFAULT ON NULL CURRENT_DATE,
    cas_rezervace           INTERVAL DAY TO SECOND DEFAULT ON NULL INTERVAL '18:00' HOUR TO MINUTE,
    datum_cas_vytvoreni     TIMESTAMP       DEFAULT ON NULL CURRENT_TIMESTAMP,
    CONSTRAINT PK_rezervace       PRIMARY KEY (ID_rezervace),
    CONSTRAINT FK_rez_zamestnanec FOREIGN KEY (ID_zamestnanec) REFERENCES Zamestnanec,
    CONSTRAINT FK_rez_zakaznik    FOREIGN KEY (ID_zakaznik)    REFERENCES Zakaznik
);

CREATE TABLE Rezervace_stolu (
    cislo_stolu     NUMERIC(3,0)   NOT NULL,
    cislo_mistnosti NUMBER         NOT NULL,
    ID_rezervace    NUMBER         NOT NULL,
    CONSTRAINT FK_rezstolu_stul_mistnost    FOREIGN KEY (cislo_stolu, cislo_mistnosti)  REFERENCES Stul,
    CONSTRAINT FK_rezstolu_rezervace        FOREIGN KEY (ID_rezervace) REFERENCES Rezervace
);

CREATE TABLE Objednavka (
    ID_objednavka           NUMBER GENERATED ALWAYS as IDENTITY,
    ID_rezervace            NUMBER,
    ID_zamestnanec          NUMBER      NOT NULL,
    ID_zakaznik             NUMBER      NOT NULL,
    datum_cas_vytvoreni     TIMESTAMP   DEFAULT ON NULL CURRENT_TIMESTAMP,
    CONSTRAINT PK_objednavka      PRIMARY KEY (ID_objednavka),
    CONSTRAINT FK_obj_rezervace   FOREIGN KEY (ID_rezervace)   REFERENCES Rezervace,
    CONSTRAINT FK_obj_zamestnanec FOREIGN KEY (ID_zamestnanec) REFERENCES Zamestnanec,
    CONSTRAINT FK_obj_zakaznik    FOREIGN KEY (ID_zakaznik)    REFERENCES Zakaznik
);

CREATE TABLE Objednavka_obsahuje_pokrm_napoj (
    ID_pokrm_napoj NUMBER    NOT NULL,
    ID_objednavka  NUMBER    NOT NULL,
    pocet          NUMBER    DEFAULT ON NULL '1' CHECK (pocet >= 1),
    CONSTRAINT FK_objpn_pokrm_napoj FOREIGN KEY (ID_pokrm_napoj) REFERENCES Pokrm_napoj,
    CONSTRAINT FK_objpn_objednavka  FOREIGN KEY (ID_objednavka)  REFERENCES Objednavka
);

CREATE TABLE Platba (
    ID_platba       NUMBER GENERATED ALWAYS as IDENTITY,
    ID_zamestnanec  NUMBER          NOT NULL,
    ID_objednavka   NUMBER          NOT NULL,
    castka          INT             NOT NULL CHECK (castka > 0),
    datum_a_cas     TIMESTAMP       DEFAULT ON NULL CURRENT_TIMESTAMP,
    typ_platby      VARCHAR(64)     NOT NULL CHECK (typ_platby IN ('hotovost', 'platební karta')),
    CONSTRAINT PK_platba           PRIMARY KEY (ID_platba),
    CONSTRAINT FK_plat_zamestnanec FOREIGN KEY (ID_zamestnanec) REFERENCES Zamestnanec,
    CONSTRAINT FK_plat_objednavka  FOREIGN KEY (ID_objednavka)  REFERENCES Objednavka
);


/* INSERT VALUES */
INSERT INTO Mistnost (nazev, kapacita)
VALUES ('Hlavni sal', 60);
INSERT INTO Mistnost (nazev, kapacita)
VALUES ('Malý salónek - 1. patro', 30);
INSERT INTO Mistnost
VALUES (DEFAULT, 'Snidane', 20);

INSERT INTO Stul
VALUES (1, 1, '6');
INSERT INTO Stul
VALUES (2, 1, '6');
INSERT INTO Stul
VALUES (1, 2, '2');
INSERT INTO Stul
VALUES (1, 3, '10');
INSERT INTO Stul (cislo_stolu, cislo_mistnosti)
VALUES (3, 1);
INSERT INTO Stul (cislo_stolu, cislo_mistnosti)
VALUES (4, 1);

INSERT INTO Zakaznik (jmeno, prijmeni, telefon, email)
VALUES('Jan', 'Novák', '746358404', 'novak12@gmail.com');
INSERT INTO Zakaznik (jmeno, prijmeni, telefon, email)
VALUES('Marie', 'Mrtvá', '743689432', 'marus@centrum.cz');
INSERT INTO Zakaznik (jmeno, prijmeni, telefon, email)
VALUES('Martina', 'Březová', '765467897', 'martina.brezova@seznam.cz');
INSERT INTO Zakaznik (jmeno, prijmeni, telefon, email)
VALUES('Tomáš', 'Suchý', '777456654', 'tom.suchy1@gmail.com');

INSERT INTO Pozice
VALUES('cis', 'číšník');
INSERT INTO Pozice
VALUES('kuch', 'kuchař');
INSERT INTO Pozice
VALUES('rec', 'recepční');

INSERT INTO Zamestnanec (zkratka_pozice, jmeno, prijmeni, rodne_cislo, bankovni_ucet, adresa)
VALUES ('cis', 'Luboš', 'Veverka', '6704217795', '1234567944/6210', 'Újezdská 6/17, 91881 Rosice');
INSERT INTO Zamestnanec (zkratka_pozice, jmeno, prijmeni, rodne_cislo, bankovni_ucet, adresa)
VALUES ('kuch', 'Josef', 'Franek', '9205272879', '42/2000', 'K Březince 3/756, 60200 Brno');
INSERT INTO Zamestnanec (zkratka_pozice, jmeno, prijmeni, rodne_cislo, bankovni_ucet, adresa)
VALUES ('cis', 'Sabina', 'Antošová', '9353148805', '523443-684877125/0200', 'Jenská 15, 327 33 Ostrava');
INSERT INTO Zamestnanec (zkratka_pozice, jmeno, prijmeni, rodne_cislo, bankovni_ucet, adresa)
VALUES ('rec', 'Michaela', 'Kárová', '8660010656', '357698-9775654567/6210', 'Klatovská 39/269, 61300 Brno');

INSERT INTO Telefon (ID_zamestnanec, telefon)
VALUES (1, '746358074');
INSERT INTO Telefon
VALUES (2, 1, '778875633');
INSERT INTO Telefon (ID_zamestnanec, telefon)
VALUES (2, '733725392');
INSERT INTO Telefon (ID_zamestnanec, telefon)
VALUES (3, '628342805');

INSERT INTO Ingredience (nazev)
VALUES ('vejce');
INSERT INTO Ingredience (nazev)
VALUES ('plnotučné mléko');
INSERT INTO Ingredience (nazev)
VALUES ('kuřecí prsa');
INSERT INTO Ingredience (nazev)
VALUES ('hovězí bok');
INSERT INTO Ingredience (nazev)
VALUES ('mouka pšeničná hladká');

INSERT INTO Alergen
VALUES (1, 'OBILOVINY OBSAHUJÍCÍ LEPEK');
INSERT INTO Alergen
VALUES (2, 'KORÝŠI');
INSERT INTO Alergen
VALUES (3, 'VEJCE');
INSERT INTO Alergen
VALUES (4, 'RYBY');

INSERT INTO Ingredience_obsahuje_alergen
VALUES (1, 3);
INSERT INTO Ingredience_obsahuje_alergen
VALUES (5, 1);

INSERT INTO Pokrm_napoj (nazev, doba_pripravy, hmotnost_gram, cena)
VALUES ('Kuřátko supreme s jasmínovou rýží, restovaným cukrovým hráškem a baby karotkou na sezamovém oleji', '35 minut', 200, 268);
INSERT INTO Pokrm_napoj (nazev, doba_pripravy, hmotnost_gram, cena)
VALUES ('Cheesecake z bílé čokolády', '5 minut', NULL, 129);
INSERT INTO Pokrm_napoj (nazev, typ, obsah_alkoholu, objem_ml, cena)
VALUES ('Domácí třešňová limonáda', 'nápoj', 0, 400, 65);
INSERT INTO Pokrm_napoj (nazev, typ, obsah_alkoholu, objem_ml, cena)
VALUES ('Espresso', 'nápoj', 0, NULL, 46);

INSERT INTO Ingredience_v_pokrmu_napoji (ID_pokrm_napoj, ID_ingredience, mnozstvi)
VALUES (1, 3, 150);
INSERT INTO Ingredience_v_pokrmu_napoji (ID_pokrm_napoj, ID_ingredience, mnozstvi)
VALUES (2, 5, 100);
INSERT INTO Ingredience_v_pokrmu_napoji (ID_pokrm_napoj, ID_ingredience, mnozstvi)
VALUES (2, 1, 4);

INSERT INTO Rezervace (ID_zamestnanec, ID_zakaznik, datum_rezervace, cas_rezervace)
VALUES (1, 1, '25-MAR-2022', DEFAULT);
INSERT INTO Rezervace (ID_zamestnanec, ID_zakaznik, datum_rezervace, cas_rezervace)
VALUES (1, 1, '27-MAR-2022', INTERVAL '20:00' HOUR TO MINUTE);
INSERT INTO Rezervace (ID_zamestnanec, ID_zakaznik, datum_rezervace, cas_rezervace)
VALUES (1, 1, '27-MAR-2022', INTERVAL '20:00' HOUR TO MINUTE);

INSERT INTO Rezervace_stolu (cislo_stolu, cislo_mistnosti, ID_rezervace)
VALUES (2, 1, 2);
INSERT INTO Rezervace_stolu (cislo_stolu, cislo_mistnosti, ID_rezervace)
VALUES (4, 1, 2);

INSERT INTO Objednavka (ID_zamestnanec, ID_zakaznik)
VALUES (1, 1);
INSERT INTO Objednavka (ID_rezervace, ID_zamestnanec, ID_zakaznik)
VALUES (1, 1, 2);
INSERT INTO Objednavka (ID_zamestnanec, ID_zakaznik)
VALUES (3, 3);

INSERT INTO Objednavka_obsahuje_pokrm_napoj (ID_pokrm_napoj, ID_objednavka)
VALUES (2, 1);
INSERT INTO Objednavka_obsahuje_pokrm_napoj (ID_pokrm_napoj, ID_objednavka, pocet)
VALUES (2, 1, 4);
INSERT INTO Objednavka_obsahuje_pokrm_napoj (ID_pokrm_napoj, ID_objednavka)
VALUES (2, 2);
INSERT INTO Objednavka_obsahuje_pokrm_napoj (ID_pokrm_napoj, ID_objednavka, pocet)
VALUES (1, 3, 2);

INSERT INTO Platba (ID_zamestnanec, ID_objednavka, castka, typ_platby)
VALUES (1, 1, 775, 'platební karta');
INSERT INTO Platba (ID_zamestnanec, ID_objednavka, castka, typ_platby)
VALUES (1, 1, 35, 'platební karta');
INSERT INTO Platba (ID_zamestnanec, ID_objednavka, castka, typ_platby)
VALUES (2, 3, 256, 'hotovost');


/* SHOW THE TABLES */
SELECT * FROM Mistnost;
SELECT * FROM Stul;
SELECT * FROM Zakaznik;
SELECT * FROM Pozice;
SELECT * FROM Zamestnanec;
SELECT * FROM Telefon;
SELECT * FROM Ingredience;
SELECT * FROM Alergen;
SELECT * FROM Ingredience_obsahuje_alergen;
SELECT * FROM Pokrm_napoj;
SELECT * FROM Ingredience_v_pokrmu_napoji;
SELECT * FROM Rezervace;
SELECT * FROM Rezervace_stolu;
SELECT * FROM Objednavka;
SELECT * FROM Objednavka_obsahuje_pokrm_napoj;
SELECT * FROM Platba;
